class AppConstants:
    MODE_EDIT = "edit"
    MODE_PREVIEW = "preview"
    SAVE = "save"
    DISCARD = "discard"
    CANCEL = "cancel"


class Messages:
    COPIED = "已复制到剪贴板"
    SAVED = "已保存"
    UNSAVED_CHANGES = "当前内容未保存，是否保存更改？"
    CONFIRM_DELETE_PROMPT = '确定要删除提示词"{name}"吗？'
    SEARCH_PLACEHOLDER = "搜索 Prompt、分类、标签..."
    SEARCH_NO_RESULTS = "无匹配结果\n\n提示: Ctrl+F 聚焦搜索 | Ctrl+S 保存 | Esc 关闭"
    IMPORT_SUCCESS = "成功导入 {count} 个文件"
    CREATE_FAILED = "创建失败"
    SETTINGS_SAVED = "设置已保存"
    BATCH_DELETE_WARNING = "文件将移至回收站，可在回收站中恢复"
    TEMPLATE_DIR_NAME = "我的模板"
    SIDEBAR_TITLE = "Prompt 库"
    SECTION_CATEGORIES = "项目 / 分类"
    ALL_PROMPTS = "全部 Prompt"
    FAVORITES = "收藏"
    RECENTLY_USED = "最近使用"
    NEW_FROM_CLIPBOARD = "从剪贴板新建"
    NEW_PROMPT = "新建"
    IMPORT = "导入"
    TEMPLATE = "模板"
    COMPOSER = "组合器"
    EDIT = "编辑"
    PREVIEW = "预览"
    SMART_TEMPLATE = "智能模板化"
    COPY = "复制"
    SAVE = "保存"
    MORE = "更多"
    WORD_COUNT = "字数"
    LAST_EDITED = "最近编辑"
    SAVED_STATUS = "已保存"
    UNSAVED_STATUS = "未保存"
    MARKDOWN = "Markdown"
